/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.tdd.gossiping

import io.kotest.core.spec.style.WordSpec
import io.kotest.matchers.shouldBe

class GossipDriverSpec : WordSpec({
    "Gossip driver" should {
        "init finishGossip method" {
            val roadMap = listOf("1")
            GossipDriver().finishGossip(roadMap) shouldBe "never"
        }

        "return 1 when 2 drivers have same 1 route" {
            val roadMap = listOf("1", "1")
            GossipDriver().finishGossip(roadMap) shouldBe "1"
        }

        "return never when 2 drivers have different 1 route" {
            val roadMap = listOf("1", "2")
            GossipDriver().finishGossip(roadMap) shouldBe "never"
        }

        "return never when multiple drivers have different 1 route" {
            val roadMap = listOf("1", "1" ,"3")
            GossipDriver().finishGossip(roadMap) shouldBe "never"
        }

    }
})
