/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.tdd.gossiping

import io.kotest.core.spec.style.WordSpec

class GossipDriverSpec: WordSpec({
    "Gossip driver" should {
        "init finishGossip method" {
            val roadMap = listOf('1')
            GossipDriver.finishGossip(roadMap).shouldBe 'never'
        }
    }
})
